const aliases = {
    "automatic market maker": ["amm", "amms", "automatic-market-maker", "automatic-market-makers"],
    "decentralized application": ["dapp", "dapps", "decentralized app", "decentralized apps", "decentralized applications"],
    "decentralized finance": ["defi"],
    "decentralized exchange": ["dex", "decentralized exchanges"],
    "layer-2": ["l2", "layer 2"],
    "liquidity provider": ["lp", "lps", "liquidity providers"],
    "non-fungible token": ["nft", "nfts", "non-fungible tokens"],
    "aggregator": ["defi aggregator", "defi aggregators"],
    "bitcoin": ["btc"],
    "ethereum": ["eth"],
    "inter-blockchain": ["inter blockchain"],
    "invoice": ["invoices"],
    "merchant": ["merchants"],
    "multi-chain": ["multi chain"],
    "on-chain": ["on chain"],
    "cross-chain": ["cross chain"],
    "oracle": ["oracles", "price oracle", "price oracles"],
    "prediction market": ["prediction markets"],
    "proof-of-stake": ["proof of stake", "pos"],
    "proof-of-work": ["proof of work", "pow"],
    "smart-contract": ["smart contract", "smart contracts"],
    "stablecoin": ["stable coin", "stable coins", "stablecoins"],
    "swapping": ["swap", "swaps"],
    "synthetic asset": ["synthetic assets"],
    "zk-rollup": ["zk rollup"],
    "zk-snark": ["zk snark", "zk snarks"]
}

export default aliases;