const glossary = [
  "API",
  "Aggregation",
  "AMM",
  "Automatic market maker",
  "Asset management",
  "Atomic swap",
  "Bitcoin",
  "Borrowing",
  "Browser",
  "Data",
  "Derivatives",
  "Dapp",
  "Decentralized app",
  "DeFi",
  "Decentralized finance",
  "DEX",
  "Decentralized exchange",
  "ERC20",
  "Ethereum",
  "Farming",
  "Governance",
  "Insurance",
  "Inter-blockchain",
  "Interoperability",
  "Invoice",
  "L2",
  "Layer 2",
  "Lending",
  "Liquidity pool",
  "LP",
  "Liquidity provider",
  "Liquidity protocol",
  "Merchant",
  "Marketplace",
  "Multi-chain",
  "Non-fungible token",
  "NFT",
  "On-chain",
  "Cross-chain",
  "Open-source",
  "Oracle",
  "Pegged",
  "Platform",
  "Prediction market",
  "Payment",
  "Privacy",
  "Proof of stake",
  "Proof of work",
  "Rewards",
  "Smart contract",
  "Stablecoin",
  "Staking",
  "Swapping",
  "Synthetic asset",
  "Trading",
  "Wallet",
  "Web3",
  "Yield",
  "zk-Rollup",
  "zk-SNARKS",
]

export default glossary;