const glossary = [
  "automatic market maker",
  "asset management",
  "atomic swap",
  "bitcoin",
  "blockchain",
  "borrowing",
  "cryptocurrency",
  "derivatives",
  "decentralized application",
  "decentralized finance",
  "decentralized exchange",
  "erc20",
  "ethereum",
  "farming",
  "farming aggregator",
  "governance",
  "insurance",
  "inter-blockchain",
  "interoperability",
  "invoice",
  "layer-2",
  "lending",
  "liquidity aggregator",
  "liquidity pool",
  "liquidity provider",
  "liquidity protocol",
  "merchant",
  "marketplace",
  "multi-chain",
  "non-fungible token",
  "on-chain",
  "cross-chain",
  "oracle",
  "prediction market",
  "proof-of-stake",
  "proof-of-work",
  "rewards",
  "smart-contract",
  "stablecoin",
  "staking",
  "swapping",
  "synthetic asset",
  "trading",
  "uniswap",
  "web3",
  "yield farming",
  "zk-rollup",
  "zk-snarks",
]

module.exports = glossary;